# Generated by Django 6.0.7 on 2026-07-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionpayout',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('gcash', 'GCash'), ('maya', 'Maya'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payslip',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('gcash', 'GCash'), ('maya', 'Maya'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
