# Generated by Django 6.0.7 on 2026-07-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_commissionpayout_is_paid_commissionpayout_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesagent',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesagent',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesagent',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Xendit disbursement channel code, e.g. BDO, BPI, GCASH, PAYMAYA.', max_length=20),
        ),
    ]
