# Generated by Django 6.0.7 on 2026-07-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salesagent_bank_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesagent',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='salesagent',
            name='bank_bic',
            field=models.CharField(blank=True, help_text='Bank Identifier Code, used for PayMongo transfers.', max_length=20),
        ),
        migrations.AddField(
            model_name='salesagent',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
