# Generated by Django 6.0.7 on 2026-07-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_branch_employee_branch'),
        ('payroll', '0004_remove_salesagent_bank_code_salesagent_bank_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesagent',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='employees.branch'),
        ),
        migrations.AlterField(
            model_name='salesagent',
            name='bank_bic',
            field=models.CharField(blank=True, help_text='Bank Identifier Code.', max_length=20),
        ),
    ]
