# Generated by Django 6.0.7 on 2026-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='available_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='max_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='work_setup',
            field=models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Work From Home'), ('hybrid', 'Hybrid')], default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('probationary', 'Probationary'), ('contractual', 'Contractual'), ('project_based', 'Project-based'), ('seasonal', 'Seasonal')], max_length=20),
        ),
    ]
